### ISSUE TITLE
Tracking lost for frame

### ISSUE THREAD

**Issue by shehroze37-zz** [tum-vision/lsd_slam#36]
Hi Im using Lsd SLam with images collected with parrot drone and trying to make lsd slam work with parrot. In one of the data sets I collect it says tracking lost for frame, whats causing that to happen ? 

Im using java to turn the images to gray scale and changing their original resolution from 640 x 360 to 640 x 480 and Im using the same calibration file from LSD_slam room. It does builds some of the map but then tracking is lost so are the changes Ive done, affecting that in any case??

Cheers !

**Comment by rbarthseas** [comment]
Yes I have the same issue. Tracking is lost after a number of frames (100-150), although the scene in the image is still very similar.

I think in my case it might have to do that one of my sent images is corrupted. My camera driver sometimes does not produce a proper image, so that might confuse the lsd-slam.

After tracking is lost, is does not find the frame again unfortunately. 

I am not trying to set the dynamic parameters to see if they can be set less sensitive to failure.

Best,
Ruud

**Comment by romulogcerqueira** [comment]
Was someone able to solve? I have this same problem.

**Comment by anathan** [comment]
This can also be caused by aggressive auto brightness or autofocus.
