### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by rbarthseas** [tum-vision/lsd_slam#37]
Hi,

I have a question regarding the time of a keyframe. In the ROS msg, it has the following field: float64 time. 

What time does this field represent? The time the keyframe was published, or perhaps the time of the source image where the keyframe was based on?

For my application I need to know to which source image the keyframe's pointcloud corresponds to.

Thanks for the help,
Ruud

**Comment by JakobEngel** [comment]
Hi Ruud,
I guess it should be the passed-along time from the ros::Image message the KF was created from. However as I've never used it, I'm not sure its actually that is implemented correctly ;). In order to find the corresponding image, passing along the image ID is probably the cleaner option.
Best,
Jakob

**Comment by rbarthseas** [comment]
Thanks Jakob,

I will try to verify what the time in the keyframe.msg corresponds to and report back here when I did.

Best,
Ruud
