### ISSUE TITLE
dataset_slam not getting past GUI

### ISSUE THREAD

**Issue by ryersonkhan** [tum-vision/lsd_slam#42]
System:
Ubuntu 14.04 64bit
rosdistro: indigo
rosversion: 1.11.9
OpenCV 2.4.10.1 (Compiled with CUD Support)

I initialize roscore in a terminal. Loads fine and accepts connections.

I then, in another terminal window, run the command:

rkhan@rkhanXPS:~/repos/rosbuild_ws$ rosrun lsd_slam_core dataset_slam _files:=/home/rkhan/Downloads/LSD_room/images/ _hz:=0 _calib:=/home/rkhan/Downloads/LSD_room/cameraCalibration.cfg

This is the dataset provided on the site.

The following output is show from the software:
Reading Calibration from file /home/rkhan/Downloads/LSD_room/cameraCalibration.cfg ... found!
found ATAN camera model, building rectifier.
Input resolution: 640 480
In: 0.397386 0.783197 0.417784 0.482498 0.000000
Out: 0.397386 0.783197 0.417784 0.482498 0.000000
Output resolution: 640 480
Prepped Warp matrices
Started  constraint search thread!
Started optimization thread 
Started mapping thread!
found 2702 image files in folder /home/rkhan/Downloads/LSD_room/images/!
Doing Random initialization!
started image display thread!
Done Random initialization!
init done 
opengl support available

At this point the program sits idle. In the program "top", I see it using 2%-3% of CPU load, but that's it.
There is another window shown "DebugWindow DEPTH", but it is "frozen"/unreponsive from it's creation and turns grey/black by Ubuntu to indicate as such. There's no image in it and it's size is very small.

Please help, thank you.

**Comment by ryersonkhan** [comment]
I got it to work, but it's a really bad solution.

I installed Ubuntu 12.04, OpenCV 2.4.8 with ROS fuerte. That's how it worked.

Can this please be made compatible with Ubuntu 14.04, OpenCV 2.4.10 and ROS Indigo? I know the instructions on the ReadMe say things about 14.04 and Indigo, but it seems quite untested and things do not work on more than one PC.

Thanks so much for the library, however. It's quite good.

**Comment by henn1001** [comment]
the problem is OpenCV WITH_QT=ON 
build opencv without it and it should work - i don't know why though

**Comment by JakobEngel** [comment]
Yes, it has something to do with OpenCV's QT-based image display and multi-threading. 
I already moved all cv::imshow into a separate thread, but apparently that didn't help... and as it works on my setup, its somewhat hard to debug / fix. Also I'm not entirely sure how to use cv::imshow properly in a multi-threaded context, i.e. what you can and cannot do.

One thing you could try quickly is to move XInitThreads(); from main(..) in  main_live_odometry.cpp to the beginning of displayThreadLoop() in ImageDisplay_OpenCV.cpp. (as well as the corresponding header inclusion).
If that doesn't fix it, the only thing left to try is to move displayThreadLoop() to the main thread, and do everything else in another thread - shouldn't be too much work either.

Or - and this is probably the best option - migrate to an image display GUI of your choice: All you have to do is re-implement  
- int waitKey(int milliseconds);
- void displayImage(const char\* windowName, const cv::Mat& image, bool autoSize = true);
- void closeAllWindows();

as defined in ImageDisplay.h; preferably in a separate .cpp which then can be linked to instead of  ImageDisplay_OpenCV.cpp
